- name: check nvm shell script
  stat:
    path: "{{ nvm_root }}/nvm.sh"
  register: nvm_sh

- name: check npm version
  stat:
    path: "{{ npm_path }}"
  register: npm_sh

- block:
  - file:
      path: "{{ system_user_home }}/.bashrc"
      state: touch
      mode: 0644
      owner: "{{ system_user }}"
      group: "{{ system_group }}"

  - name: download nvm
    get_url:
      url: https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh
      dest: /tmp/install.sh
      mode: 0777

  - name: change owner of nvm install file
    file:
      path: /tmp/install.sh
      owner: "{{ system_user }}"
      group: "{{ system_group }}"

  - name: install nvm
    shell: /tmp/install.sh
    args:
      executable: /bin/bash
    environment:
      HOME: "{{ system_user_home }}"

  - name: install node version and set it as default
    shell: ". {{ system_user_home }}/.nvm/nvm.sh && nvm install {{ node_version }} && nvm use {{ node_version }}"
    args:
      executable: /bin/bash
    environment:
      HOME: "{{ system_user_home }}"

  when: nvm_sh.stat.exists == False or npm_sh.stat.exists == False

