---
- name: Add ntp
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - ntp

- name: check ntp
  service:
    name: ntp
    state: started
